# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags: "[0-9]+.[0-9]+.[0-9]+"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: get_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mysql-backup-agent:${{ steps.get_version.outputs.version }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
